/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.otus;

import com.google.common.collect.HashMultiset;
import com.google.common.collect.Multiset;

public class HelloOtus {
    public static void main(String... args) {
        Multiset<String> counts = HashMultiset.create();
        counts.add("one");
        counts.add("two");
        counts.add("two");

        System.out.println(counts);
    }
}
